# Generated by Django 3.2.9 on 2021-11-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkylarkLeaksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoTitle', max_length=256)),
                ('raw_url', models.CharField(default='', max_length=1024)),
                ('go_url', models.CharField(default='', max_length=1024)),
                ('book_name', models.CharField(default='', max_length=256)),
                ('group_name', models.CharField(default='', max_length=256)),
                ('abstract', models.TextField(default='')),
                ('search_rule_id', models.PositiveBigIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('content_updated_at', models.DateTimeField()),
                ('first_published_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('paper_created_at', models.DateTimeField()),
                ('paper_updated_at', models.DateTimeField()),
                ('ext_info', models.TextField(default='{}')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'skylark_leaks',
            },
        ),
        migrations.CreateModel(
            name='SkylarkSearchRulesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(default='', max_length=64)),
                ('content', models.TextField(default='')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('last_search_time', models.DateTimeField(auto_now_add=True)),
                ('interval', models.PositiveIntegerField(default=15)),
                ('ext_info', models.TextField(default='{}')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'skylark_search_rules',
            },
        ),
    ]
